### ISSUE TITLE
Pre-trained model(Imagenet) results 

### ISSUE THREAD

**Issue by kaminocode** [rick-chang/OneNet#1]
I reproduced the result on the ring image using the pretrained model on imagenet. Since the image is 640 x 480, the last 32 pixels where left out. Still the image doesn't seem to match with result shown on the paper. 
![cs_69999](https://user-images.githubusercontent.com/8917417/30216535-f415c26c-94d0-11e7-9f24-fe3a45f4f588.jpg)

Further the patches are very much visible. Do you do some kind of post processing after stitching the 64 x 64 images?

**Comment by kaminocode** [comment]
Further on this particular image the results are poor. How should I change the alpha parameter if I'm using the pretrained model on imagenet?
![original_img](https://user-images.githubusercontent.com/8917417/30216795-c8db76fe-94d1-11e7-8e5c-4d8c60b977a3.png) ![parrot](https://user-images.githubusercontent.com/8917417/30216794-c8d79a8e-94d1-11e7-877b-08d163f99ffd.jpg)

**Comment by githublzb** [comment]
when I run paper_demo.py, there was an error:
Traceback (most recent call last):
  File "/home/GithubDown/OneNet/admm/paper_demo.py", line 432, in <module>
    testset_filelist = load_data.load_testset_path_list()
  File "../projector/load_celeb.py", line 74, in load_testset_path_list
    return load_testset_path()['image_path'].tolist()
AttributeError: 'list' object has no attribute 'tolist'
How do I overcome this?
Thanks ahead.
